infolder: onshots/
outfile: oneshots.json
outfolder: datasets/
tokenizer:
  tokenizer_model: microsoft/phi-2
  min_tokens: 512
  max_tokens: 2048
  chunk_overlap: 0

patterns:
  split: (?<!\w\.\w)(?<![A-Z][a-z]\.)(?<=\.|\?|\!)\s
  remove:
    - (\d+)D&D.*\|.*?(Not for resale\. Permission granted to print and photocopy this document for personal use only.)
    - "Art: Shutterstock.*"
    - Reformation:.*?(extent necessary to .*|&..\\.* \$.*\$.*)$
    - ZIWKHFKDUDFWHUVFRQYLQFHG8OWKXUXVWROHDYH

embedder:
  embedding_model: BAAI/bge-small-en-v1.5

inference:
  hugginface-api-key: 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
  reranking-model-id: BAAI/bge-reranker-large
