downloads:
    DMBasicRules.pdf: https://media.wizards.com/2014/downloads/dnd/DMBasicRulesv.0.3.pdf
    PlayerBasicRules.pdf: https://media.wizards.com/2018/dnd/downloads/DnD_BasicRules_2018.pdf
    RiseOfTiamat.pdf: https://media.wizards.com/2014/downloads/dnd/RiseTiamatSupplementv0.2_Printer.pdf
    HoardOfTheDragonQueen.pdf: https://media.wizards.com/2014/downloads/dnd/HoardDragonQueen_Supplement_PF_v0.3.pdf

outfolder: downloads/

patterns:
    code: '"code": (\d+)'
    message: '"message": "([^"]+)"'
    reason: '"reason": "([^"]+)"'
