version: 1
disable_existing_loggers: 0
formatters:
  default:
    format: "%(asctime)s:%(levelname)s:%(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
loggers:
  basicLogger:
    level: ERROR #
    handlers: [console]
    propagate: 1
root:
  level: INFO #
  handlers: [console]
  propagate: 1
