tokenizer:
  tokenizer_model: microsoft/phi-2
  chunk_size: 2024
  chunk_overlap:

patterns:
  replacements:
    " \ufb03": "ffi"
    "\ufb03": "ffi"
    "\u0003": ""
    "\u0011": ""
    "\u0014": ""
    "\u0017": ""
    "\u00117": ""
    "\u016b": " "
    "\xa0": " "
    # "\u00a0": " "
    "\u2018": "'"
    "\u2019": "'"
    "\u201c": '"'
    "\u201d": '"'
    "•": "-"
    "\u2011": "-"
    "\u2013": "-"
    "\u2014": "-"
    # "\u2022": "-"
    "\u00a7": ""
    "\u00d7": "x"
    "\u0234": "fi"
    "\ufb01": "fi"
    "\u038d": "ff"
    "\ufb00": "ff"
    "\u025d": "ffi"
    "\u025e": "ffl"
    "\u0235": "fl"
    "\ufb02": "fl"
    "\u0106": "5"
    "\u0018": "5"
    "\u001a": "7"
    "\u2026": "..."
    "\u0396": "Z"
    "\u000e": "+ "
    # "\u0015": "0 "
    "e ffects": "effects"
    # "\u0013": ""

embedder:
  embedding_model: BAAI/bge-small-en-v1.5

inference:
  hugginface-api-key: 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
  reranking-model-id: BAAI/bge-reranker-large
